version: '3'

services:
  orders-api:
    # build:
    #   context: .
    image: "vanko1/orders-api:latest"
    container_name: orders-api
    platform: linux/x86_64
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
